---
# handlers file for ansible-ntp

- name: Restart NTP daemon
  service:
    name: "{{ ntp_daemon }}"
    state: restarted
    enabled: true
  when: ntp_enabled
  become: yes

- name: Stop NTP daemon
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when: not ntp_enabled
